"""Stage 7: Documentation.

Produces the README a developer actually needs to run and use the generated
service: setup instructions, the API surface as generated (not the full
theoretical spec -- only what implementation actually built), and a pointer
back to the architecture and requirements docs for the reasoning behind it.
Kept as a distinct stage (rather than folded into implementation) because it
is `optional` in the SDLC graph: a run under time pressure can bypass it
without blocking release, whereas the code and tests cannot be skipped.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from orchestrator.agents.base import Agent
from orchestrator.contracts import ArtifactKind

if TYPE_CHECKING:
    from orchestrator.core.graph import StageNode
    from orchestrator.core.state import RunState


class DocsAgent(Agent):
    stage_name = "docs"

    async def run(self, node: StageNode, state: RunState) -> object:
        code_ctx = state.context.get("code", reader=self.stage_name) or {}
        caps = code_ctx.get("capabilities", {})
        readme = self._render(state, caps)
        artifact = self.artifact("README.md", ArtifactKind.DOC, readme)

        decision = self.decision(
            "what does the README document?",
            "only the endpoints and capabilities implementation actually generated",
            "documenting an aspirational API that doesn't match the generated code is worse "
            "than no documentation -- a reader would trust it and hit a 404",
            confidence=0.85,
        )

        return self.result(
            summary="generated README documenting the endpoints actually implemented",
            artifacts=(artifact,),
            decisions=(decision,),
        )

    def _render(self, state: RunState, caps: dict) -> str:
        title = state.requirement.title
        lines = [
            f"# {title}",
            "",
            "Generated by the agentic SDLC orchestrator. See `docs/requirements.md`, "
            "`docs/architecture.md` and `docs/plan.md` for how this came to be built this way.",
            "",
            "## Run it",
            "",
            "```bash",
            "pip install fastapi uvicorn",
            "uvicorn app.main:app --reload",
            "```",
            "",
            "## API",
            "",
            "| Method | Path | Description |",
            "|---|---|---|",
            "| POST | `/api/urls` | create a shortened URL |",
            "| GET | `/{code}` | redirect to the original long URL |",
            "| GET | `/api/urls/{code}` | fetch metadata for a code |",
            "| DELETE | `/api/urls/{code}` | revoke a code |",
        ]
        if caps.get("stats"):
            lines.append("| GET | `/api/urls/{code}/stats` | click analytics for a code |")
        lines += ["| GET | `/health` | liveness check |", ""]

        lines.append("## Capabilities in this build")
        for name, enabled in caps.items():
            status = "enabled" if enabled else "not enabled for this requirement"
            lines.append(f"- {name}: {status}")
        lines.append("")
        lines.append(
            "See `docs/security_review.md` for known limitations and `docs/risk_register.md` "
            "for validation status and trade-offs."
        )
        return "\n".join(lines) + "\n"
